"use client";

import { useRef, useState } from "react";

interface AttachedProofReportData {
  tlsProof: string | null;
  tlsProofFormat: string | null;
  tlsProofFileName: string | null;
  tlsProofStatus: string | null;
  tlsProofServerName: string | null;
  tlsProofTime: string | null;
  tlsProofSentData: string | null;
  tlsProofRecvData: string | null;
}

interface TlsProofUploaderProps {
  reportId: string;
  onProofAttached: (reportData: AttachedProofReportData) => void;
}

const MAX_PROOF_SIZE_BYTES = 1024 * 1024;

export default function TlsProofUploader({
  reportId,
  onProofAttached,
}: TlsProofUploaderProps) {
  const [status, setStatus] = useState<"idle" | "uploading" | "success" | "error">(
    "idle"
  );
  const [error, setError] = useState("");
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFile = (file: File) => {
    setError("");

    if (!file.name.endsWith(".tlsn")) {
      setSelectedFile(null);
      setStatus("error");
      setError("Upload the .presentation.tlsn file generated by the tlsn-docker prover.");
      return;
    }

    if (file.size === 0) {
      setSelectedFile(null);
      setStatus("error");
      setError("The selected proof file is empty.");
      return;
    }

    if (file.size > MAX_PROOF_SIZE_BYTES) {
      setSelectedFile(null);
      setStatus("error");
      setError("Proof files larger than 1 MB are not supported.");
      return;
    }

    setSelectedFile(file);
    setStatus("idle");
  };

  const handleDrop = (event: React.DragEvent) => {
    event.preventDefault();
    const file = event.dataTransfer.files[0];
    if (file) {
      handleFile(file);
    }
  };

  const handleUpload = async () => {
    if (!selectedFile) {
      return;
    }

    setStatus("uploading");
    setError("");

    try {
      const formData = new FormData();
      formData.append("proof", selectedFile);

      const response = await fetch(`/api/reports/${reportId}/verify-proof`, {
        method: "POST",
        body: formData,
      });

      const data = await response.json();

      if (!response.ok) {
        setError(data.details || data.error || "Upload failed");
        setStatus("error");
        return;
      }

      setStatus("success");
      onProofAttached(data.report);
    } catch {
      setError("Network error. Please try again.");
      setStatus("error");
    }
  };

  return (
    <div className="space-y-4">
      {status !== "success" && (
        <div
          onDrop={handleDrop}
          onDragOver={(event) => event.preventDefault()}
          onClick={() => fileInputRef.current?.click()}
          className="border-2 border-dashed border-gray-700 hover:border-green-600 rounded-xl p-8 text-center cursor-pointer transition-colors group"
        >
          <input
            ref={fileInputRef}
            type="file"
            accept=".tlsn,application/octet-stream"
            className="hidden"
            onChange={(event) => {
              const file = event.target.files?.[0];
              if (file) {
                handleFile(file);
              }
            }}
          />

          <div className="flex flex-col items-center gap-3">
            <div className="w-12 h-12 bg-gray-800 rounded-xl flex items-center justify-center group-hover:bg-green-900/30 transition-colors">
              <svg
                className="w-6 h-6 text-gray-400 group-hover:text-green-400 transition-colors"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={1.5}
                  d="M9 12.75l3 3m0 0l3-3m-3 3v-7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
            </div>
            <div>
              <p className="text-sm font-medium text-gray-300">
                Drop your{" "}
                <span className="font-mono text-green-400">.presentation.tlsn</span>{" "}
                proof here
              </p>
              <p className="text-xs text-gray-500 mt-1">
                Generated by the dockerized TLSNotary prover and verified server-side through the TLSNotary API
              </p>
            </div>
          </div>
        </div>
      )}

      {selectedFile && status !== "success" && (
        <div className="bg-gray-800/50 border border-gray-700 rounded-xl p-5">
          <div className="flex items-center justify-between mb-3">
            <h4 className="text-sm font-semibold text-white flex items-center gap-2">
              <svg
                className="w-4 h-4 text-green-400"
                fill="currentColor"
                viewBox="0 0 20 20"
              >
                <path
                  fillRule="evenodd"
                  d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                  clipRule="evenodd"
                />
              </svg>
              Proof Ready to Verify
            </h4>
            <button
              onClick={() => {
                setSelectedFile(null);
                setStatus("idle");
                setError("");
              }}
              className="text-xs text-gray-500 hover:text-red-400"
            >
              Remove
            </button>
          </div>

          <div className="grid grid-cols-2 gap-3 text-xs">
            <div>
              <p className="text-gray-500 mb-0.5">Filename</p>
              <p className="text-white font-mono break-all">{selectedFile.name}</p>
            </div>
            <div>
              <p className="text-gray-500 mb-0.5">Size</p>
              <p className="text-white">
                {(selectedFile.size / 1024).toFixed(1)} KB
              </p>
            </div>
          </div>

          <div className="mt-3 rounded-lg border border-blue-700/30 bg-blue-950/20 p-3 text-xs text-blue-400">
            The app will verify this presentation through the dockerized TLSNotary
            API and then attach the verified metadata to the report.
          </div>

          <button
            onClick={handleUpload}
            disabled={status === "uploading"}
            className="mt-4 w-full bg-green-500 hover:bg-green-400 disabled:opacity-50 text-black font-bold py-2.5 rounded-lg text-sm transition-colors"
          >
            {status === "uploading"
              ? "Verifying and Attaching Proof..."
              : "Attach TLSNotary Proof to Report"}
          </button>
        </div>
      )}

      {status === "success" && (
        <div className="bg-green-950/30 border border-green-700/50 rounded-xl p-5 text-center">
          <div className="text-green-400 text-2xl mb-2">✓</div>
          <p className="text-green-400 font-semibold text-sm">
            TLSNotary Proof Attached!
          </p>
          <p className="text-gray-400 text-xs mt-1">
            The uploaded presentation was verified by the TLSNotary API and attached
            to the report.
          </p>
        </div>
      )}

      {status === "error" && error && (
        <div className="bg-red-950/30 border border-red-700/50 rounded-xl p-4 text-red-400 text-sm">
          {error}
        </div>
      )}

      <div className="bg-blue-950/20 border border-blue-700/30 rounded-xl p-4">
        <p className="text-blue-400 text-xs font-medium mb-1.5">
          What is a TLSNotary Proof?
        </p>
        <p className="text-blue-500 text-xs leading-relaxed">
          TLSNotary proofs cryptographically verify that an HTTP session took place
          between a prover and a server. Attaching one to your bug report proves
          you genuinely observed the vulnerability, and the app re-verifies the
          uploaded presentation through the dockerized TLSNotary API before
          accepting it.
        </p>
        <a
          href="https://tlsnotary.org"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-400 hover:underline text-xs mt-2 inline-block"
        >
          Learn more about TLSNotary →
        </a>
      </div>
    </div>
  );
}
