"use client";

import { useState, useRef } from "react";
import { parseTlsProof, validateTlsProofStructure } from "@/lib/tlsProof";

interface TlsProofUploaderProps {
  reportId: string;
  onProofAttached: (result: {
    serverName: string;
    sessionTime: string;
    sentLen: number;
    recvLen: number;
    hasSignature: boolean;
  }) => void;
}

export default function TlsProofUploader({
  reportId,
  onProofAttached,
}: TlsProofUploaderProps) {
  const [status, setStatus] = useState<
    "idle" | "parsing" | "uploading" | "success" | "error"
  >("idle");
  const [error, setError] = useState("");
  const [preview, setPreview] = useState<ReturnType<typeof parseTlsProof> | null>(null);
  const [proofJson, setProofJson] = useState("");
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFile = async (file: File) => {
    setStatus("parsing");
    setError("");
    setPreview(null);

    try {
      const text = await file.text();
      const validationError = validateTlsProofStructure(text);
      if (validationError) {
        setError(`Invalid proof: ${validationError}`);
        setStatus("error");
        return;
      }

      const parsed = parseTlsProof(text);
      setPreview(parsed);
      setProofJson(text);
      setStatus("idle");
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to parse proof file");
      setStatus("error");
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    const file = e.dataTransfer.files[0];
    if (file) handleFile(file);
  };

  const handleUpload = async () => {
    if (!proofJson) return;
    setStatus("uploading");
    setError("");

    try {
      const res = await fetch(`/api/reports/${reportId}/verify-proof`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ proof: proofJson }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.details || data.error || "Upload failed");
        setStatus("error");
        return;
      }

      setStatus("success");
      onProofAttached(data.summary);
    } catch {
      setError("Network error. Please try again.");
      setStatus("error");
    }
  };

  return (
    <div className="space-y-4">
      {/* Drop zone */}
      {status !== "success" && (
        <div
          onDrop={handleDrop}
          onDragOver={(e) => e.preventDefault()}
          onClick={() => fileInputRef.current?.click()}
          className="border-2 border-dashed border-gray-700 hover:border-green-600 rounded-xl p-8 text-center cursor-pointer transition-colors group"
        >
          <input
            ref={fileInputRef}
            type="file"
            accept=".json,application/json"
            className="hidden"
            onChange={(e) => {
              const file = e.target.files?.[0];
              if (file) handleFile(file);
            }}
          />
          <div className="flex flex-col items-center gap-3">
            <div className="w-12 h-12 bg-gray-800 rounded-xl flex items-center justify-center group-hover:bg-green-900/30 transition-colors">
              <svg
                className="w-6 h-6 text-gray-400 group-hover:text-green-400 transition-colors"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={1.5}
                  d="M9 12.75l3 3m0 0l3-3m-3 3v-7.5M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
            </div>
            <div>
              <p className="text-sm font-medium text-gray-300">
                Drop your{" "}
                <span className="font-mono text-green-400">proof.json</span>{" "}
                here
              </p>
              <p className="text-xs text-gray-500 mt-1">
                Generated by the TLSNotary prover — proves your HTTP session was real
              </p>
            </div>
          </div>
          {status === "parsing" && (
            <p className="text-xs text-yellow-400 mt-3 animate-pulse">
              Parsing proof...
            </p>
          )}
        </div>
      )}

      {/* Proof Preview */}
      {preview && status !== "success" && (
        <div className="bg-gray-800/50 border border-gray-700 rounded-xl p-5">
          <div className="flex items-center justify-between mb-3">
            <h4 className="text-sm font-semibold text-white flex items-center gap-2">
              <svg
                className="w-4 h-4 text-green-400"
                fill="currentColor"
                viewBox="0 0 20 20"
              >
                <path
                  fillRule="evenodd"
                  d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                  clipRule="evenodd"
                />
              </svg>
              Proof Parsed Successfully
            </h4>
            <button
              onClick={() => {
                setPreview(null);
                setProofJson("");
              }}
              className="text-xs text-gray-500 hover:text-red-400"
            >
              Remove
            </button>
          </div>

          <div className="grid grid-cols-2 gap-3 text-xs">
            <div>
              <p className="text-gray-500 mb-0.5">Server</p>
              <p className="text-white font-mono font-medium">
                {preview.serverName}
              </p>
            </div>
            <div>
              <p className="text-gray-500 mb-0.5">Session Time</p>
              <p className="text-white">
                {preview.sessionTime.toLocaleString()}
              </p>
            </div>
            <div>
              <p className="text-gray-500 mb-0.5">Bytes Sent</p>
              <p className="text-white">{preview.sentLen.toLocaleString()}</p>
            </div>
            <div>
              <p className="text-gray-500 mb-0.5">Bytes Received</p>
              <p className="text-white">{preview.recvLen.toLocaleString()}</p>
            </div>
            <div>
              <p className="text-gray-500 mb-0.5">Notary Signature</p>
              <p className={preview.hasSignature ? "text-green-400" : "text-yellow-400"}>
                {preview.hasSignature ? "Present ✓" : "Self-attested"}
              </p>
            </div>
            <div>
              <p className="text-gray-500 mb-0.5">Merkle Root</p>
              <p className="text-gray-400 font-mono text-xs truncate">
                {preview.merkleRoot.substring(0, 16)}...
              </p>
            </div>
          </div>

          {preview.sentDataPreview && (
            <div className="mt-3">
              <p className="text-gray-500 text-xs mb-1">HTTP Request Preview (redacted)</p>
              <pre className="bg-gray-900 rounded-lg p-3 text-xs text-green-300 font-mono overflow-auto max-h-24 whitespace-pre-wrap">
                {preview.sentDataPreview.substring(0, 300)}
                {preview.sentDataPreview.length > 300 ? "..." : ""}
              </pre>
            </div>
          )}

          <button
            onClick={handleUpload}
            disabled={status === "uploading"}
            className="mt-4 w-full bg-green-500 hover:bg-green-400 disabled:opacity-50 text-black font-bold py-2.5 rounded-lg text-sm transition-colors"
          >
            {status === "uploading"
              ? "Attaching Proof..."
              : "Attach TLSNotary Proof to Report"}
          </button>
        </div>
      )}

      {/* Success */}
      {status === "success" && (
        <div className="bg-green-950/30 border border-green-700/50 rounded-xl p-5 text-center">
          <div className="text-green-400 text-2xl mb-2">✓</div>
          <p className="text-green-400 font-semibold text-sm">
            TLSNotary Proof Attached!
          </p>
          <p className="text-gray-400 text-xs mt-1">
            Your vulnerability report is now cryptographically verified.
          </p>
        </div>
      )}

      {/* Error */}
      {status === "error" && error && (
        <div className="bg-red-950/30 border border-red-700/50 rounded-xl p-4 text-red-400 text-sm">
          {error}
        </div>
      )}

      {/* Info box */}
      <div className="bg-blue-950/20 border border-blue-700/30 rounded-xl p-4">
        <p className="text-blue-400 text-xs font-medium mb-1.5">
          What is a TLSNotary Proof?
        </p>
        <p className="text-blue-500 text-xs leading-relaxed">
          TLSNotary proofs cryptographically verify that an HTTP session took place
          between a prover and a server. Attaching one to your bug report proves
          you genuinely observed the vulnerability — not just crafted a theoretical PoC.
          The proof shows the server name, timestamp, and selected request/response data
          without revealing your session tokens or other private information.
        </p>
        <a
          href="https://tlsnotary.org"
          target="_blank"
          rel="noopener noreferrer"
          className="text-blue-400 hover:underline text-xs mt-2 inline-block"
        >
          Learn more about TLSNotary →
        </a>
      </div>
    </div>
  );
}
