import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/auth";
import {
  TlsProofVerificationError,
  type VerifiedTlsPresentation,
  verifyTlsPresentationWithApi,
} from "@/lib/tlsProofApi";

export const runtime = "nodejs";

/**
 * POST /api/reports/[id]/verify-proof
 *
 * Accepts a TLSNotary `.presentation.tlsn` proof file generated by the
 * dockerized tlsn flow, verifies it via the TLSNotary HTTP API, and
 * stores the verified metadata alongside the report.
 */
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await getSession();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id } = await params;

  const report = await prisma.report.findUnique({
    where: { id },
    include: { program: { include: { company: true } } },
  });

  if (!report) {
    return NextResponse.json({ error: "Report not found" }, { status: 404 });
  }

  // Only the reporter or company owner can attach a proof
  const isReporter = report.reporterId === session.userId;
  const isCompanyOwner = report.program.company.userId === session.userId;

  if (!isReporter && !isCompanyOwner) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  const contentType = request.headers.get("content-type") || "";
  if (!contentType.includes("multipart/form-data")) {
    return NextResponse.json(
      {
        error: "Invalid upload",
        details: "Upload a TLSNotary .presentation.tlsn file as multipart/form-data.",
      },
      { status: 400 }
    );
  }

  const formData = await request.formData();
  const proofPart = formData.get("proof");

  if (!(proofPart instanceof File)) {
    return NextResponse.json(
      {
        error: "Missing proof file",
        details: "Attach the TLSNotary .presentation.tlsn file in the 'proof' field.",
      },
      { status: 400 }
    );
  }

  if (!proofPart.name.endsWith(".tlsn")) {
    return NextResponse.json(
      {
        error: "Invalid proof file",
        details: "Only TLSNotary .tlsn presentation files are supported.",
        status: "invalid",
      },
      { status: 400 }
    );
  }

  const proofBuffer = Buffer.from(await proofPart.arrayBuffer());
  if (proofBuffer.length === 0) {
    return NextResponse.json(
      {
        error: "Invalid proof file",
        details: "The uploaded TLSNotary presentation file was empty.",
        status: "invalid",
      },
      { status: 400 }
    );
  }

  let parsed: VerifiedTlsPresentation;
  try {
    parsed = await verifyTlsPresentationWithApi(proofBuffer, proofPart.name);
  } catch (error) {
    const details =
      error instanceof Error ? error.message : "Unknown TLSNotary verification error";
    const statusCode =
      error instanceof TlsProofVerificationError ? error.statusCode : 500;

    return NextResponse.json(
      {
        error:
          statusCode === 400
            ? "Invalid TLSNotary presentation"
            : "TLSNotary verification API unavailable",
        details,
        status: statusCode === 400 ? "invalid" : "error",
      },
      { status: statusCode }
    );
  }

  const updatedReport = await prisma.report.update({
    where: { id },
    data: {
      tlsProof: proofBuffer.toString("base64"),
      tlsProofFormat: "presentation_tlsn",
      tlsProofFileName: proofPart.name,
      tlsProofStatus: "verified",
      tlsProofServerName: parsed.serverName,
      tlsProofTime: new Date(parsed.sessionTime),
      tlsProofSentData: parsed.sentData || null,
      tlsProofRecvData: parsed.recvData || null,
    },
    select: {
      tlsProof: true,
      tlsProofFormat: true,
      tlsProofFileName: true,
      tlsProofStatus: true,
      tlsProofServerName: true,
      tlsProofTime: true,
      tlsProofSentData: true,
      tlsProofRecvData: true,
    },
  });

  return NextResponse.json({
    message: "TLSNotary presentation attached successfully",
    report: {
      tlsProof: updatedReport.tlsProof,
      tlsProofFormat: updatedReport.tlsProofFormat,
      tlsProofFileName: updatedReport.tlsProofFileName,
      tlsProofStatus: updatedReport.tlsProofStatus,
      tlsProofServerName: updatedReport.tlsProofServerName,
      tlsProofTime: updatedReport.tlsProofTime?.toISOString() ?? null,
      tlsProofSentData: updatedReport.tlsProofSentData,
      tlsProofRecvData: updatedReport.tlsProofRecvData,
    },
    summary: {
      serverName: parsed.serverName,
      sessionTime: parsed.sessionTime,
      sentLen: parsed.sentLen,
      recvLen: parsed.recvLen,
      hasSignature: true,
      proofFormat: "presentation_tlsn",
      proofFileName: proofPart.name,
    },
  });
}

/**
 * DELETE /api/reports/[id]/verify-proof
 * Removes the attached TLSNotary proof from a report.
 */
export async function DELETE(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const session = await getSession();
  if (!session) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id } = await params;

  const report = await prisma.report.findUnique({
    where: { id },
    select: { reporterId: true },
  });

  if (!report) {
    return NextResponse.json({ error: "Report not found" }, { status: 404 });
  }

  if (report.reporterId !== session.userId) {
    return NextResponse.json({ error: "Forbidden" }, { status: 403 });
  }

  await prisma.report.update({
    where: { id },
    data: {
      tlsProof: null,
      tlsProofFormat: null,
      tlsProofFileName: null,
      tlsProofStatus: null,
      tlsProofServerName: null,
      tlsProofTime: null,
      tlsProofSentData: null,
      tlsProofRecvData: null,
    },
  });

  return NextResponse.json({ message: "Proof removed" });
}
